[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
[[redirects]]
from = "/payment/success"
to = "/index.html"
status = 200

[dev]
  command = "npm run dev"
  targetPort = 3000
  port = 8888
  publish = "dist"
  autoLaunch = true
  framework = "#custom"